config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_validation { self.email = email.downcase }
  before_create :create_remember_token

  def self.find_by_email(email)
    find_by(email: email.downcase)
  end

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    # to_sメソッドを呼び出しているのは、nilトークンを扱えるようにするためです
    # nil.to_sは""になる
    # Digest::SHA1.hexdigest("")でも文字列は発行される
    # https://railstutorial.jp/chapters/sign-in-sign-out?version=4.0
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :signed_in?, :current_user

  # ログインするたびにremember_tokenは更新されるのでなりすましを防げる
  def sign_in(user)
    remember_token = User.new_remember_token
    # 永続化クッキー(cookies.permanent)
    # http://railsdoc.com/references/cookies
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    @current_user = user
  end

  def signed_in?
    !!current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url, notice: 'ログインしました'
    else
      flash.now[:alert] = 'emailかパスワードが間違っています'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to _users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def t_model(path)
    t("activerecord.models.#{path}")
  end

  def t_model_attr(path)
    t("activerecord.attributes.#{path}")
  end

  def price_unit(price)
    "#{number_with_delimiter(price)}円"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.haml
- unless flash.empty?
  #flash
    - if notice
      .alert.alert-success{role: 'alert'}
        = notice
    - if alert
      .alert.alert-danger{role: 'alert'}
        = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsNonDevise
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #wrapper
      %header#header
        %p#header-logo= link_to('RailsNonDevise', root_path)
        %ul#header-nav
          - if signed_in?
            %li= "ログインユーザー：#{current_user.name}"
            %li= link_to 'sign out', session_path(current_user), method: :delete
          - else
            %li= link_to 'sign up', new_user_path
            %li= link_to 'sign in', new_session_path
      #container
        = render 'layouts/flash'
        = yield

app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name

  .form-inputs
    = f.input :email

  .form-inputs
    = f.input :password

  .form-inputs
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 ユーザー一覧

%table.table
  %thead
    %tr
      %th ID
      %th ユーザー名
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/users/new.html.haml
%h1 新規ユーザー

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path